version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g typescript
      - npm install -g concurrently
      - npm install -g yarn
      - npm install
      - npm ci
      - npm run server_install
      - cd client && yarn
      #- npm run client_install
      
  pre_build:
    commands:
      - npm cache clean --force
      #- ulimit -n 524288
      - echo Build started on `date`
      - echo Compiling the Node.js code...

  build:
    commands:
      - npm run server_build # This command should be defined in your package.json and generate the dist folder

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  enable-symlinks: true
  files:
    #- client/dist/**/*
    - server/dist/**/*
    - package.json
    - package-lock.json
    - server/package.json
    - server/package-lock.json
    - server/.env
    - node_modules/**/*
    - server/node_modules/**/*
    # - client/node_modules/**/*
    #- client/package.json
    #- client/package-lock.json
    #- client/public/index.html
    #- client/src/index.js

  name: 'my-artifact'
     
# cache:
#   paths:
#     - 'node_modules/**/*'
#     - 'client/node_modules/**/*'
#     - 'server/node_modules/**/*' 


